### ISSUE TITLE
How

### ISSUE THREAD

**Issue by OFark** [djjonas123/VolumeChanger#1]
How did you use SoudvolumeView in iCue, I can't figure it out?

**Comment by djjonas123** [comment]
I guess you figured it out since you closed  the threat. However I have found a bug where the SVW program changes mic level with the audio for discord. This is a fault in the program which I can’t directly fix. I would like to know if you have this same problem, I have a workaround which i can push if you encounter the same error.

**Comment by OFark** [comment]
Is this not tying the overall mic volume to the Headset volume? I've not actually tried it in-game yet, I was hoping the effect wouldn't translate to other people. What have you done?

**Comment by djjonas123** [comment]
I pushed two updated batch files (iCUE does supports batch files). They now set the mic volume to 100 and a small timeout inbetween volumechange and mic change is needed because the volumechange takes longer to do. This however does means that you can't spam the button because it needs about half a second per activation. In order to counter this I changed the volume change from 5 to 10% which you can make bigger if you like.
